#!/bin/bash

set -e


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER ${APP_USER} WITH ENCRYPTED PASSWORD '${APP_USER_PASSWORD}';
    CREATE DATABASE ${APP_DATABASE_NAME} WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'ja_JP.utf8' LC_CTYPE = 'ja_JP.utf8';

EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$APP_DATABASE_NAME" <<-EOSQL

    CREATE SCHEMA ${APP_SCHEMA};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ${APP_SCHEMA} TO ${APP_USER};

EOSQL